# Generated by Django 6.0.3 on 2026-04-07 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('scooter', 'Scooter')], max_length=20)),
                ('is_parked', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('image', models.FileField(upload_to='vehicles/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkease.user')),
            ],
        ),
    ]
