# Generated by Django 6.0.3 on 2026-04-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkease', '0002_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='vehicles/'),
        ),
    ]
