# Generated by Django 6.0.3 on 2026-04-07 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkease', '0005_admin_name_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkease.apartment'),
        ),
        migrations.AddField(
            model_name='user',
            name='flat_no',
            field=models.CharField(default='XXXX', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
