# Generated by Django 6.0.3 on 2026-04-22 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkease', '0006_user_apartment_user_flat_no_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Apartment',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
