# Generated by Django 6.0.3 on 2026-04-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkease', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
