# Generated by Django 6.0.3 on 2026-04-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkease', '0009_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
