# Generated by Django 5.1.4 on 2026-04-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkease', '0011_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nick_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
