# Generated by Django 6.0.3 on 2026-04-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkease', '0012_user_nick_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('2W', 'Two Wheeler'), ('4W', 'Four Wheeler')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='flat_no',
            field=models.CharField(default='XXX', max_length=10),
        ),
    ]
