# Generated by Django 6.0.3 on 2026-04-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkease', '0014_vehicle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='rc_book',
            field=models.FileField(blank=True, null=True, upload_to='rc_books/'),
        ),
    ]
