# Generated by Django 6.0.3 on 2026-05-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkease', '0016_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
