# Generated by Django 5.1.4 on 2026-05-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkease', '0018_vehicle_parking_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
