# Generated by Django 5.1.4 on 2026-05-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkease', '0019_vehicle_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
