# Generated by Django 6.0.3 on 2026-05-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkease', '0020_vehicle_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
