# Generated by Django 6.0.3 on 2026-05-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkease', '0021_vehicle_is_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='security_photos/')),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
