# Generated by Django 6.0.3 on 2026-05-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkease', '0022_securitystaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitystaff',
            name='date_of_birth',
            field=models.CharField(max_length=10),
        ),
    ]
