# Generated by Django 6.0.3 on 2026-05-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkease', '0023_alter_securitystaff_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_in',
            field=models.BooleanField(default=True),
        ),
    ]
